# Script för att skapa NewtonBank databas

DROP SCHEMA IF EXISTS NewtonTestTool;
CREATE SCHEMA NewtonTestTool CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL ON NewtonBank.* TO root@localhost IDENTIFIED BY 'root';

USE NewtonTestTool;

CREATE TABLE User (
	uId INT UNSIGNED NOT NULL AUTO_INCREMENT,
	uName VARCHAR(10) NOT NULL,
	uPassword VARCHAR(8) NOT NULL,
	uEmail VARCHAR(30) NOT NULL,
	groupType ENUM('STUDENT', 'TEACHER', 'ADMIN') NOT NULL,
	PRIMARY KEY(Id)
) ENGINE=INNODB;

CREATE TABLE Test (
		tId INT UNSIGNED NOT NULL AUTO_INCREMENT,
		tTitle VARCHAR(10) NOT NULL,
		tOpen DATE NOT NULL,
		tClose DATE NOT NULL,
		tTime VARCHAR(10),
		tShowCorrect BOOLEAN NOT NULL DEFAULT FALSE,
		tDone BOOLEAN DEFAULT FALSE,
		tTotalscore TINYINT UNSIGNED DEFAULT 0,
		tGrade TINYINT UNSIGNED DEFAULT 0,
		tFeedback VARCHAR(500),
		uId INT UNSIGNED NOT NULL,
		PRIMARY KEY(tId),
	 	FOREIGN KEY (uId) REFERENCES User(uId) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1001;

CREATE TABLE Question (
		qId INT UNSIGNED NOT NULL AUTO_INCREMENT,
		question VARCHAR(300) NOT NULL,
		category ENUM('SELECTION', 'CHOICE', 'REORDER', 'ANSWER') NOT NULL,
		score TINYINT UNSIGNED NOT NULL,
		tId INT UNSIGNED NOT NULL,
		PRIMARY KEY(qId),
	 	FOREIGN KEY (tId) REFERENCES Test(tId) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE Answer (
		aId INT UNSIGNED NOT NULL AUTO_INCREMENT,
		answer VARCHAR(20) NOT NULL,
		textanswer VARCHAR(300),
		correct BOOLEAN NOT NULL DEFAULT FALSE,
		correctOrder TINYINT NOT NULL,
		qId INT UNSIGNED NOT NULL,
		PRIMARY KEY(aId),
	 	FOREIGN KEY (qId) REFERENCES Question(qId) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE Resource (
		rcId INT UNSIGNED NOT NULL AUTO_INCREMENT,
		url VARCHAR(300) NOT NULL,
		qId INT UNSIGNED NOT NULL,
		PRIMARY KEY(rcId),
	 	FOREIGN KEY (qId) REFERENCES Question(qId) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

-- CREATE TABLE Result (
-- 		rsId INT UNSIGNED NOT NULL AUTO_INCREMENT,
-- 		tId INT UNSIGNED NOT NULL,
-- 		score TINYINT UNSIGNED DEFAULT 0,
-- 		grade TINYINT UNSIGNED DEFAULT 0,
-- 		feedback VARCHAR(500),
-- 		PRIMARY KEY(rsId),
-- 	 	FOREIGN KEY (tId) REFERENCES Test(tId) ON UPDATE CASCADE ON DELETE CASCADE
-- ) ENGINE=INNODB;
